spring.application.name=Project3
spring.datasource.type=com.zaxxer.hikari.HikariDataSource
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://postgres.gcilrmwcjhuywvmglben:fX4z8A8b0Qtk7JGZ@aws-1-us-west-2.pooler.supabase.com:5432/postgres

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.gcilrmwcjhuywvmglben
spring.datasource.password=fX4z8A8b0Qtk7JGZ

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

server.forward-headers-strategy=native
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

spring.datasource.hikari.initialization-fail-timeout=1