spring.application.name=Project3

spring.datasource.url=jdbc:postgresql://db.gcilrmwcjhuywvmglben.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=fX4z8A8b0Qtk7JGZ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

server.forward-headers-strategy=native
server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true

spring.datasource.hikari.initialization-fail-timeout=1